[project]
name = "mailer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
	"fastapi>=0.95.0",
	"uvicorn[standard]>=0.22.0",
	"python-dotenv>=1.0.0",
	"pytest>=7.0",
	"httpx>=0.24.0",
	"email-validator>=2.0.0"
]
